### ISSUE TITLE
Fix colons and tabulation in list results

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#194]
Change to match the patterns in figma. Fix on the seach results and details page.

The content of terms in description lists have inconsistent use of colons. 

The [examples in the design system](https://design-system.service.gov.uk/components/summary-list/) **don't** use colons. I assume because the `<dl>` itself creates logical separation and we don't need colons.

<img src="https://github.com/ministryofjustice/find-moj-data/assets/1306705/5d2a8289-214a-4559-942b-eda2f0f3d1be" width="500" />

Can we create a Selenium test for this? 🤔

**Comment by MatMoore** [comment]
@jemnery I think this inconsistency has come about because we've diverged from the design.

The figma doesn't use the summary list component, and instead just has one item per line with a colon. I think we just implemented this pattern of our own accord early on and never updated it, and the one in the figma is how it should be.

 https://www.figma.com/file/zTOVhHRnWfxRJqH6Gr8cIc/Catalogue-sketches?type=design&node-id=203-2121&mode=design&t=YocOJ80P7hF7KanZ-0

Previously I corrected this on the details page by using a govuk list instead of govuk summary list. The result looks like this:

![Image](https://github.com/ministryofjustice/find-moj-data/assets/87579/38442e41-8d36-4d2b-a5c3-9d6f5b9ea61d)

I reckon we should do the same thing on the search results page. Not using the summary list also means we can use a horizontal line break to separate the actual results, as in this DFE example:

![Image](https://github.com/ministryofjustice/find-moj-data/assets/87579/b66970db-cb9d-49ae-a3f3-51f00f875cff)

What do you think @alex-vonfeldmann ?

**Comment by jemnery** [comment]
I like the idea of using a `<hr>` to separate the results

**Comment by YvanMOJdigital** [comment]
wait for ur playback

**Comment by YvanMOJdigital** [comment]
Remove tags/retention period/first created from results view. 

Need more research to better understand what people want from results page.
