### ISSUE TITLE
Decide what framework to use for the catalogue API

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#262]
## What
- We want to build a new API service. What technology do we want to implement this with? We are not required to use anything in particular, so choose what suits the team.
- We'll have a dev meeting to discuss options
  - If we have consensus we can go with a solution and write an ADR right away
  - Otherwise we can take away things to investigate and reconvene to make a decision
  - Include design of the registration API
  - Only name and description to be included in the API at this stage

## Why
- We are going to build a new interface to manually register arbitrary metadata to the catalogue, i.e. anything that cannot be ingested through a ready made ingestion source for whatever reason.
- This will make use of the library we've already written to interface with the catalogue, but we want to make this a service now so we can extend it to machine-driven updates at some point.

## Assumptions
- We probably won't directly recycle code from the previous [data platform APIs](https://github.com/ministryofjustice/data-platform) we built on modernisation platform, but we can use it for inspiration. These APIs dealt with data ingestion, not just metadata.
- We don't need AWS API gateway - this was useful when we were building on modernisation platform and using lambdas, but we are now on cloud platform and no longer need a separate gateway to handle things like auth and rate limiting.
- We don't want everything to be modifiable via API, e.g. the domain model, glossary will be more controlled.
- We will need a way to read metadata as well as write it - in order to populate domain options etc in the new interface.
- We will keep it simple and not try to handle ingestion of multiple entities at once. If a related entity doesn't exist, return an error.

## Out of scope
- We can discuss the metadata we want to accept separately. For now, assume it will be similar to what we are already capturing in [data-catalogue-metadata](https://github.com/ministryofjustice/data-catalogue-metadata)
- Removing or archiving metadata

## Options to discuss
- In the firebreak last year, we explored FastAPI, and we have some example code available for this. However we don't have to 
- Django / Django Rest Framework
- Flask
- ???

### Things to consider
- Total cost of ownership
- Skills in the team
- Integration with EntraID
- Ease of API development

## Output
- ADR for technology choice to build and operate our catalogue APIs
- Tickets for the work involved to set up the new service and implement a first endpoint

## Additional resources
- [Previous API design](https://docs.google.com/spreadsheets/d/1SF0m4j-_NSLD6yyuJizZC0F06jHPkAvLWheuLeHORJk/edit#gid=626736695)
- [Service manual: choosing a technology](https://www.gov.uk/service-manual/technology/choosing-technology-an-introduction)

**Comment by jemnery** [comment]
https://jamboard.google.com/d/1E4QmMtSdBw-9__lIuhnZp8YGzJTG5CMKr7uJq9zIPRQ/viewer?pli=1&mtt=us4lct7lo5tg&f=0

**Comment by MatMoore** [comment]
In light of other decisions (build the service as a monolith for now) we may not need an API at all. 

It will depend on the approach taken as a result of https://github.com/ministryofjustice/data-catalogue-metadata/issues/14
i.e. what is the path for ingesting metadata from outside of the analytical platform?

Should we need an API, we will build it into the existing Django app rather than making it a separate service. We have already converted our models to use pydantic so we can trivially serialise/deserialise these. Django can be overkill for an API service, but since we already have it as a dependency there is no additional overhead from choosing it here.

Django Rest Framework and Django Ninja are both libraries we can pull in top of django if we need to. These both integrate with swagger for reference documentation.
