### ISSUE TITLE
Spike: Try out business attributes feature

### ISSUE THREAD

**Issue by MatMoore** [ministryofjustice/find-moj-data#426]
https://datahubproject.io/docs/businessattributes/

This needs to be enabled through a `businessAttributeEntityEnabled` config option.

If it's not added as a helm variable yet, we can switch it on via `extraEnvs`

Be able to clearly demonstrate the value and key differences of

- tags
- glossary terms
- business attributes

---

> A Business Attribute, as its name implies, is an attribute with a business focus. It embodies the traits or properties of an entity within a business framework. This attribute is a crucial piece of data for a business, utilised to define or control the entity throughout the organisation. If a business process or concept is depicted as a comprehensive logical model, then each Business Attribute can be considered as an individual component within that model. While business names and descriptions are generally managed through glossary terms, Business Attributes encompass additional characteristics such as data quality rules/assertions, data privacy markers, data usage protocols, standard tags, and supplementary documentation, alongside Names and Descriptions

**Comment by YvanMOJdigital** [comment]
Potential usecase for data dictionary. Test of feature not implementation. Needs DIP validation?

**Comment by murdo-moj** [comment]
https://datahubspace.slack.com/archives/CV2KB471C/p1718284691101579

> the Business Attribute has some Tags and Terms linked to it, and when I attach it to a Dataset the Attribute kinds of brings the Tags and Terms with it

> It will help to centralize the management of Terms and Tags and description across multiple fields that have the same purpose.

**Comment by murdo-moj** [comment]
Business attributes are connected to columns or datasets ![Image](https://github.com/user-attachments/assets/6024808a-ddb0-4203-bf8a-a89fcdd97e91)

**Comment by murdo-moj** [comment]
![Image](https://github.com/user-attachments/assets/7e22648e-91f7-486c-a278-8ad473550614)
business attributes can be attached to fields in the UI

**Comment by murdo-moj** [comment]
### Summary

Business attributes are an upcoming feature of Datahub. Business attributes simplify the management of key fields/attributes across datasets. For example, **offender_id** could be used across several tables in the prison datasets, Business attributes allows a central definition, tagging, and assignment of glossary terms to that field, so changes are easier.

Adding a business attribute to a field appends all descriptions, tags and glossary terms to that field definition.

Business attributes are available only through the UI right now. 

### Do business attributes solve our desire for a data dictionary?

No. Business attributes allow us to better define per-field business information, but per table or datasets information can't be held. Also, since all descriptions of business attributes are pulled through to the field level, we should be mindful of keeping the descriptions appropriate in length for their audience (ie users might not want a 2000 word explanation on an id field)

**Comment by murdo-moj** [comment]
Business attributes would be useful for SCD2 type fields like RECORD_START_DATE etc
