### ISSUE TITLE
Re-test CADeT ingestion for Athena compatibility

### ISSUE THREAD

**Issue by jemnery** [ministryofjustice/find-moj-data#508]
JHP has flagged a coming upgrade to the dbt athena adapter version - This is plan to be merged to main by **10th July.**

There are some changes to how metadata are generated, which are what datahub uses for ingestion. see https://docs.getdbt.com/docs/dbt-versions/core-upgrade/upgrading-to-v1.7#for-consumers-of-dbt-artifacts-metadata

original slack message form Jacob:
https://mojdt.slack.com/archives/C03B3UTAJJ1/p1719310300786479

We'll need to use the test branch https://github.com/moj-analytical-services/create-a-derived-table/tree/dbt-athena-upgrade-182 to locally generate the docs and run our ingestion complete with it's customisations to test we can still run ingestion of cadet as we had intended

**Comment by LavMatt** [comment]
Update on this:
- Have locally created a `manifest` and `catalogue` file using the [dbt-athena-upgrade-182](https://github.com/moj-analytical-services/create-a-derived-table/tree/dbt-athena-upgrade-182) branch. This was done for the dev cadet environment (not prod) as it was being difficult for prod. Still the files should be created using the new schema.
- I got a `run_results.json` from matt price, who had deployed some em models using the new branch.
- I uploaded to `mojap-derived-tables/catalogue_static_dbt_docs/new-athena-version-docs`
- I cleared all dbt data fro datahub and ingested the above files into dev datahub.
- As you'll see from dev the data have ingested, but not been added to databases, but i think it's more because of different parsing rules  (cadet model filepath >> database.table) for dev dbs, that's it's not added any datasets to databases- Probably why it was really quick too

**Comment by LavMatt** [comment]
The upgrade is being delayed for a week and will now happen on 17 July

**Comment by LavMatt** [comment]
**It doesn't appear that the upgrade will impact our ingestion of create-a-derived-table dbt data.**

The test ingestions have needed to be run in slightly different way to what will happen in production cadet though - i.e. created locally using the development environment of cadet.

There were some issues with the ingestion but these were related to using the cadet dev environment - which creates database names in a way we do not account for in our custom ingestion scripts (adding a `_dev_dbt` suffix).

We could potentially improve how we infer the database name from the manifest file as there are values in it we could use that are representative of the database name post parsing of the dbt model filename.

**Comment by LavMatt** [comment]
As i had made some improvements to our custom dbt ingestions with regard to how we infer the athena database name - in order to be able to test out the upgrade that was in the cadet dev environment - i tidied these up into a PR: https://github.com/ministryofjustice/data-catalogue/pull/195

Will mean we can now test our ingestions using the dev cadet environment which will be where new cadet features are rolled out to in advance of prod deployment
