### ISSUE TITLE
Sort production front end URL

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#546]
find-moj-data.service.justice.gov.uk

I think this is it above, but check against domain rules held by ops eng [here](https://technical-guidance.service.justice.gov.uk/documentation/standards/naming-domains.html)

**Comment by MatMoore** [comment]
Have sent an email to operations engineering to discuss next steps. find-moj-data.service.justice.gov.uk looks right based on my reading of the rules

**Comment by MatMoore** [comment]
Notes on progress so far

The prod url delegates to the prod hosted zone:
`find-moj-data.service.justice.gov.uk. 783 IN SOA ns-1872.awsdns-42.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400`

The dev/test/preprod, also delegate to the prod hosted zone, so maybe we don't need the extra ones? Cloud platform guidance recommends managing everything from one zone, so maybe that's how I have set it up by following the guide.

I'm not sure yet if the hosted zone has been populated. Expecting kubernetes to set this up via ExternalDNS

None of the domains yet resolve an IP (may just be waiting for caches to expire atm since I only just deployed it)

**Comment by MatMoore** [comment]
I've also added a service pod to the dev environment, so that I can run aws commands to inspect the state of things.

`aws route53 get-hosted-zone --id [...]`

The ID is printed in the concourse logs for applying terraform

This needs to be rolled out to the other environments as well, but not necessarily in this ticket

**Comment by MatMoore** [comment]
Prod is working now. I'll create a separate task for the non production envs.
