### ISSUE TITLE
Create disaster recovery plan

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/find-moj-data#602]
## Requirements

- [ ] Identify potential shutdown 'disasters'
- [ ] itemise the runbook pages / sections we'll need with restore instructions
    - [ ] write disaster recovery pages / sections
- [ ] timescales and sla expectations
- [ ] Create followup tickets with tests for recovery plans

**Comment by murdo-moj** [comment]
Here's ChatGPT's attempt

### Disaster Recovery Plan for Django Application Hosted on AWS

#### **1. Overview**

This Disaster Recovery Plan (DRP) outlines the procedures to follow in the event of a disaster that affects the Django application hosted on AWS. The goal is to minimize downtime and data loss while ensuring a quick and efficient recovery.

#### **2. Scope**

- **Application:** Django-based Python application
- **Hosting:** AWS (Amazon Web Services)
- **Database:** Hosted on AWS (e.g., RDS, Aurora)
- **Backend Services:** Served by DataHub
- **Key Components:**
  - Django application code
  - Database (e.g., PostgreSQL, MySQL)
  - Static and media files
  - Backend services

#### **3. Risk Assessment**

The following are potential risks that could disrupt the application:

- **Infrastructure Failure:** EC2 instance failure, RDS/Aurora database failure, S3 bucket issues.
- **Data Corruption:** Data corruption in the database due to application bugs or malicious attacks.
- **Security Breach:** Unauthorized access leading to data loss or compromise.
- **Natural Disasters:** Events such as earthquakes, floods, or fires affecting AWS data centers.
- **Human Error:** Accidental deletion or misconfiguration.

#### **4. Disaster Recovery Objectives**

- **Recovery Time Objective (RTO):** 1 hour
- **Recovery Point Objective (RPO):** 15 minutes

#### **5. Disaster Recovery Strategy**

##### **5.1 Backup Strategy**

- **Database Backups:**
  - Use AWS RDS automated backups and snapshots for the database. 
  - Enable point-in-time recovery for RDS instances to recover the database to any specific point within the backup retention period (e.g., 7 days).
  - Schedule regular snapshots and store them in a different AWS region.
  
- **Application Code:**
  - Store the Django application code in a version-controlled repository (e.g., Git).
  - Use AWS CodeCommit or GitHub for source control.
  - Regularly back up the repository to another location (e.g., another region or a different cloud provider).

- **Static and Media Files:**
  - Store static and media files in AWS S3.
  - Enable S3 versioning to keep multiple versions of objects and prevent data loss.
  - Set up cross-region replication for the S3 bucket to replicate files to a bucket in a different AWS region.

- **Backend DataHub Configurations:**
  - Backup DataHub configurations and metadata regularly.
  - Store backups in a secure S3 bucket with versioning enabled.

##### **5.2 Redundancy and Failover**

- **EC2 Instances:**
  - Deploy the Django application in multiple AWS Availability Zones (AZs) using an Auto Scaling Group.
  - Use Elastic Load Balancer (ELB) to distribute traffic across multiple instances.

- **Database:**
  - Enable Multi-AZ deployment for RDS/Aurora for automatic failover in case of an AZ outage.
  - Consider Read Replicas in different regions for faster recovery.

- **DataHub Services:**
  - Deploy DataHub services in multiple AZs.
  - Implement load balancing and auto-scaling for backend services.

##### **5.3 Monitoring and Alerts**

- **AWS CloudWatch:**
  - Set up CloudWatch for monitoring EC2, RDS, and S3.
  - Configure CloudWatch alarms for key metrics such as CPU usage, disk I/O, and latency.
  - Enable CloudWatch Logs for application logs and set up alerts for errors or anomalies.

- **DataHub Monitoring:**
  - Monitor DataHub service health and performance using appropriate tools (e.g., Prometheus, Grafana).
  - Set up alerts for any service disruptions or failures.

##### **5.4 Disaster Recovery Testing**

- **Regular Testing:**
  - Conduct regular DR drills to test the recovery process, including failover scenarios and data restoration.
  - Document and review the outcomes to identify areas for improvement.

- **Simulated Failures:**
  - Simulate infrastructure failures (e.g., EC2 instance termination, RDS failover) to ensure the application can recover within the defined RTO and RPO.

#### **6. Recovery Procedures**

##### **6.1 Infrastructure Recovery**

1. **EC2 Instance Failure:**
   - If an EC2 instance fails, Auto Scaling will automatically replace the instance.
   - Verify the new instance is correctly configured and receiving traffic.

2. **RDS/Aurora Database Failure:**
   - If the primary database fails, AWS will automatically failover to the standby instance in another AZ.
   - Confirm the application reconnects to the new database endpoint.

##### **6.2 Application Recovery**

1. **Code Repository Restoration:**
   - Clone the latest version of the Django application from the Git repository.
   - Deploy the application to the replacement EC2 instances.

2. **Database Restoration:**
   - If the database is corrupted, restore from the most recent RDS snapshot or point-in-time recovery.
   - Verify data integrity and application functionality.

3. **Static and Media Files Recovery:**
   - In case of S3 data loss, restore from versioned objects or cross-region replicated buckets.
   - Verify that the application can access all necessary static and media files.

##### **6.3 Backend Services Recovery (DataHub)**

1. **Service Failure:**
   - If a DataHub service fails, restart the service using AWS ECS or Kubernetes, depending on the deployment method.
   - Verify that the service is healthy and responding to requests.

2. **Configuration Recovery:**
   - Restore the most recent DataHub configuration backup from S3.
   - Apply the configurations and verify the integrity of the DataHub instance.

#### **7. Communication Plan**

- **Internal Communication:**
  - Notify the IT team immediately upon discovering a disaster.
  - Provide regular updates on the recovery process to all stakeholders.

- **External Communication:**
  - Notify customers and users about the service disruption and expected recovery time via email, social media, and application notifications.
  - Provide updates until the service is fully restored.

#### **8. Post-Disaster Review**

- **Incident Analysis:**
  - Conduct a post-mortem analysis to identify the root cause of the disaster.
  - Review the effectiveness of the DR plan and identify any gaps.

- **Plan Update:**
  - Update the DR plan based on lessons learned from the incident and any new risks identified.

#### **9. Documentation and Storage**

- **DR Plan Storage:**
  - Store a copy of the DR plan in a secure, version-controlled repository.
  - Ensure the DR plan is accessible to all key personnel even in the event of a disaster.

- **Documentation:**
  - Maintain detailed documentation of the application architecture, backup procedures, and recovery steps.
  - Regularly update the documentation to reflect any changes in the infrastructure or application.

---

This Disaster Recovery Plan is a living document and should be reviewed and updated regularly to ensure it remains effective and relevant.
