### ISSUE TITLE
🔒 Add container / image scanning to detect OS-level vulnerabilities

### ISSUE THREAD

**Issue by tom-webber** [ministryofjustice/find-moj-data#810]
### Context
We currently aren't scanning our images for any OS-level vulnerabilities. We could add a workflow step to scan our images prior to deployment to ensure we're not deploying anything unduly unsecure.

[Difference between container scanning and dependency scanning](https://docs.gitlab.com/ee/user/application_security/comparison_dependency_and_container_scanning.html#:~:text=Dependency%20Scanning%20analyzes%20your%20project,operating%20system's%20(OS)%20packages.)

[CP uses Trivy already ](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/trivy-image-scanning.html#trivy-vulnerability-scanning)
How do they feed back this?

**Comment by YvanMOJdigital** [comment]
ask @jacobwoffenden

**Comment by YvanMOJdigital** [comment]
Check with CP. may be redundant

**Comment by MatMoore** [comment]
The CP scanning only catches issues when they're already in production - we are supposed to run trivy as part of the build as well.

We can use this https://github.com/aquasecurity/trivy-action

**Comment by mitchdawson1982** [comment]
I had a call with @Gary-H9 & @jacobwoffenden earlier with regards to the vulnerability scanning results.
For the front end we have used the `python3.11-slim-buster` image and this doesn't receive updates to the OS packages.

Going forward, we should look to move the base image to `python3.11-alpine` so that we have the most recent OS image available.
Additionally we should integrate trivvy into the workflow to check images on pull request (ideally)

Helpful Links 

- AP UI Dockerfile example - https://github.com/ministryofjustice/analytical-platform-ui/blob/main/container/Dockerfile
- Trivvy workflow scanning - https://github.com/ministryofjustice/analytical-platform-ingestion-notify/blob/main/.github/workflows/scan-image.yml#L33
- Trivvy ignore file - https://github.com/ministryofjustice/analytical-platform-visual-studio-code/blob/main/.trivyignore

**Comment by MatMoore** [comment]
Some teams fail the PR if there are any high/critical alerts - but I don't think we're in a position to do this until we switch the base image. But see if we can fail if there are any NEW high/critical alerts.

We will also add trivy ignore as an escape hatch.

**Comment by MatMoore** [comment]
The workflow is now in place for FMJ.

For Datahub, I don't think there is any point adding it right now as we don't build the images ourselves. The only decision point is whether to deploy an update or not and in almost all cases we will be better off on the most recent version. It looks like Datahub do have processes in place for regularly updating their base images and we can view the scan results that are run already in cloud platform using the instructions here: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/trivy-image-scanning.html#trivy-vulnerability-scanning
