### ISSUE TITLE
🐛 Responsive tables

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/find-moj-data#915]
[PR](https://github.com/ministryofjustice/find-moj-data/pull/934)

**Comment by YvanMOJdigital** [comment]
from accessibility team recommendations report

**Comment by mitchdawson1982** [comment]
I have raised a PR however I am going to have a wider look at this, custom CSS to follow the NHS example might be a better way forward. 

[ONS](https://service-manual.ons.gov.uk/design-system/components/table/example-table-responsive)
[NHS](https://service-manual.nhs.uk/design-example/components/table/responsive?fullpage=undefined&blankpage=undefined)

- https://github.com/alphagov/govuk-design-system-backlog/issues/61#issuecomment-427380866

**Comment by mitchdawson1982** [comment]
Url sent to Matt Proctor - https://dev.find-moj-data.service.justice.gov.uk/details/table/urn:li:dataset:(urn:li:dataPlatform:dbt,cadet.awsdatacatalog.caseman.address_types,PROD)

**Comment by mitchdawson1982** [comment]
Awaiting Matt's review

**Comment by mitchdawson1982** [comment]
Notes from Matt's review

`Thank you for sending the new link through. I am happy to meet up to chat more about this if you think that will help, but here are my observations. 

1. Table looks great. It is responsive and does not fall off the page. My only question is whether 'column name' is just a placeholder for now? I am assuming this will have a more relevant heading. 
2. Any empty table cells have hidden text to advise there is no data. All looks good.
3. The heading structure is now looking spot on. All h2's for the description and the side headings. 
4. You have removed the use of 'click' from the links and the replacement works well. 

Element that needs some more work:
1. Breadcrumbs. When zoomed in, ideally breadcrumbs need to collapse otherwise they might take up too much space. There is a class you can add, "govuk-breadcrumbs--collapse-on-mobile" to achieve this. https://design-system.service.gov.uk/components/breadcrumbs/

The breadcrumb issue wasn't one that was highlighted from the review, and it is not technically an accessibility fail, more of a recommendation. 

Thanks again Mitchell, if there is anything else please let me know,`
