### ISSUE TITLE
Implement Search-to-Discovery Time metric on GA4

### ISSUE THREAD

**Issue by teeceeas** [ministryofjustice/find-moj-data#922]
As a product manager, I want to implement a metric in Google Analytics that tracks the time it takes for users to find a relevant dataset, so that I can measure user efficiency and improve the discoverability of datasets within the data catalog.

**Acceptance Criteria:
1. Track Search Initiation Event**
> Event name: search_start
> Trigger this event when a user initiates a search by typing a query into the search bar.

**2. Track Dataset Click Event**
> Event name: dataset_click
> Trigger this event when a user clicks on a dataset link in the search results or navigates to the dataset's metadata page.

**3. Calculate Time Difference**
> In GA4, you can create custom metrics that calculate the time difference between two events (search_start and dataset_click).
> You’ll need to use Google Tag Manager (GTM) to track these custom events and the timestamps of when they occur.
> A script in GTM can calculate the time elapsed between when the search_start event is triggered and when the dataset_click event occurs, storing this data as a variable.

**4. Set up a Custom Metric in GA4**
> In GA4, create a custom metric called Time to Find Dataset.
> Use the timestamp difference calculated from GTM to populate this custom metric.
> Track and report on the average time to find a relevant dataset by grouping events by session.

**Comment by MatMoore** [comment]
We will not need to add new events for this - should reuse the same ones as for @LavMatt's funnel.

We just need to agree what constitutes the start of a search.

Keep in mind that searches can be iniitated in multiple ways:

- From the home page search form
- From the search page search form
- Clicking the button
- Pressing enter
- The automatic submission when interacting with filters

Ideally we would not count visits from bookmarked links as starting the search, as this will distort the measurements.

**Comment by MatMoore** [comment]
@teeceeas, regarding this point

> In GA4, you can create custom metrics that calculate the time difference between two events (search_start and dataset_click).

As far as I can tell, the only way to do this in GA4 is within a funnel exploration, which we can enable but doesn't require any extra work on top of what we are already doing in the other tickets - it's just toggling a checkbox.

![Image](https://github.com/user-attachments/assets/d9b86ee8-79a6-40d6-b0f8-c02dffc5e01c)

Though for some reason it only shows you the *total* elapsed time, so to get an average you need to divide by the number of users who reached that step.

If this is good enough, then I think we can close this ticket. 

Otherwise, I think we will need to build something custom as described in [this community question](https://support.google.com/analytics/thread/12561399/how-to-track-time-between-different-events?hl=en), or perhaps use a different tool for this.

**Comment by MatMoore** [comment]
Conclusion - we will just use the funnel elapsed time for now. 

If other tools become available to us, then we can reconsider this. The dashboards team were also looking at https://clarity.microsoft.com/ - I don't know if this can measure time elapsed between key events but it does record sessions and integrates with Google Analytics.
